### ISSUE TITLE
The screenshots are not matching my website.

### ISSUE THREAD

**Issue by emily060866** [emily060866/navigation-highlight#1]
I keep trying to adjust the padding/width to my elements but it never matches. 

@thomasjbradley

```css
html {
  box-sizing: border-box;
  font: normal 100%/1.5 Georgia;
  line-height: 1.5;
  background-color: #fff;
  color: #2f2d13;
}

*, *::before, *::after {
  box-sizing: inherit;
}

h1 {
  font-family: "Sigmar One", cursive;
  font-size: 3rem;
  color: #b20953;
  text-align: center;
  margin: 0;
}

body {
  margin: 0;
}

header {
  background-color: #ffe500;
  text-align: center;
  padding: .75em;
}

li {
  display: inline-block;
}

a {
  color: #fff;
  text-decoration: none;
  background-color: #b2a212;
  border-radius: 4px;
  padding: .5em;
}

h2 {
  font-family: "Sigmar One", cursive;
  font-size: 1.875rem;
  color: #b20953;
  text-align: left;
}

main {
  margin: .3em;
}

footer {
  margin: .3em;
  text-align: center;
  background-color: #ffe500;
  font-size: .75rem;
  padding: .5em;
  margin-left: 0;
  margin-right: 0;
}

img {
  display: block;
  width: 100%;
}

figure {
  margin: 0;
}

.fruits {
  background-color: #b20953;
}

li:hover {
  background-color: #cc1465;
}

ul {
  margin: 0;
  padding: 0;
}

a:hover {
  background-color: #cc1465;
}

figcaption {
  padding: .75em;
}
```

- Emily
